# Generated by Django 5.0.1 on 2024-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                ("area", models.CharField(max_length=30, null=True)),
                ("dob", models.DateField()),
            ],
        ),
    ]
