# Generated by Django 5.0.1 on 2024-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
