# Generated by Django 5.0.1 on 2024-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0002_treatment_verified_alter_treatment_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="designation",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="doctor_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="hospital_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="speciality",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
