# Generated by Django 5.0.1 on 2024-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0003_treatment_designation_treatment_doctor_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="specialist",
        ),
        migrations.AddField(
            model_name="prescription",
            name="next_appointment",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="last_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="start_date",
            field=models.DateField(),
        ),
    ]
