# Generated by Django 5.0.1 on 2024-02-21 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0004_remove_prescription_specialist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient_name",
        ),
    ]
