# Generated by Django 5.0.1 on 2024-02-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0005_remove_prescription_doctor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="height",
            field=models.IntegerField(null=True),
        ),
    ]
