# Generated by Django 5.0.1 on 2024-02-21 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
        ("treatments", "0006_prescription_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treatments.treatment",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sharetreatment",
            constraint=models.UniqueConstraint(
                fields=("treatment", "doctor"), name="unique_treatment_doctor"
            ),
        ),
    ]
