# Generated by Django 5.0.1 on 2024-02-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0007_sharetreatment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="disease",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
