# Generated by Django 5.0.1 on 2024-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0008_alter_treatment_disease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="request",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="last_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
