# Generated by Django 5.0.1 on 2024-02-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0009_alter_prescription_date_alter_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="request",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="last_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="start_date",
            field=models.DateField(),
        ),
    ]
