# Generated by Django 5.0.1 on 2024-02-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0010_alter_prescription_date_alter_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="treatments.treatment",
            ),
        ),
    ]
