# Generated by Django 5.0.1 on 2024-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0011_alter_prescription_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
