# Generated by Django 4.1.2 on 2024-03-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0012_treatment_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['-last_date']},
        ),
    ]
