const medicineSuggestions = [
    "Panadol",
    "Napa",
    "Ciprobay",
    "Amoxil",
    "Glucophage",
    "Losec",
    "Flagyl",
    "Zantac",
    "Azithrocin",
    "Zyrtec",
    "Benadryl",
    "Voltaren",
    "Claritin",
    "Norvasc",
    "Lipitor",
    "Cozaar",
    "Zocor",
    "Disprin",
    "Synthroid",
    "Lasix",
    "Vasotec",
    "Plavix",
    "Zebeta",
    "Lanoxin",
    "Tenormin",
    "Zoloft",
    "Prozac",
    "Paxil",
    "Lexapro",
    "Effexor",
    "Lopressor",
    "Aciphex",
    "Protonix",
    "Neurontin",
    "Lyrica",
    "Microzide",
    "Atacand",
    "Micardis",
    "Diovan",
    "Reglan",
    "Motilium",
    "Nexium",
    "Prevacid",
    "Cymbalta",
    "Ultram",
    "Codilin",
    "Morphix",
    "Imodium",
    "Inderal",
    "Coreg"
  ];
  
  
  export default medicineSuggestions;
  