# Generated by Django 5.0.1 on 2024-02-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Consultency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=4)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.clinic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultencyDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "consultency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="doctors.consultency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=30, null=True)),
                ("dob", models.DateField()),
                ("description", models.CharField(max_length=400, null=True)),
                ("department", models.CharField(max_length=30)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("consultant", "Consultant"),
                            ("senior_consultant", "Senior Consultant"),
                            ("assistant_professor", "Assistant Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("professor", "Professor"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=10)),
                ("speciality", models.CharField(max_length=20, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degree",
                        to="doctors.doctor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultency",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultency",
                to="doctors.doctor",
            ),
        ),
        migrations.AddConstraint(
            model_name="consultencyday",
            constraint=models.UniqueConstraint(
                fields=("consultency", "day"), name="unique_consultency_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="degree",
            constraint=models.UniqueConstraint(
                fields=("doctor", "degree", "speciality"),
                name="unique_doctor_degree_speciality",
            ),
        ),
        migrations.AddConstraint(
            model_name="consultency",
            constraint=models.UniqueConstraint(
                fields=("doctor", "clinic", "room"), name="unique_doctor_clinic_room"
            ),
        ),
    ]
