# Generated by Django 5.0.1 on 2024-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
