# Generated by Django 5.0.1 on 2024-03-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_rating_rating_unique_doctor_patient"),
        ("patients", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.patient"
            ),
        ),
    ]
