# Generated by Django 5.0.1 on 2024-02-18 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="upvote",
            name="post",
        ),
        migrations.RemoveField(
            model_name="upvote",
            name="user",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Upvote",
        ),
    ]
