# Generated by Django 5.0.1 on 2024-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0011_alter_upvotepost_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reportpost",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
