# Generated by Django 5.0.1 on 2024-03-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0012_comment_update_date_post_update_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_path",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
