# Generated by Django 5.0.1 on 2024-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0013_remove_image_image_path_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
