# Generated by Django 5.0.1 on 2024-03-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0014_alter_image_caption"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.post"
                    ),
                ),
            ],
        ),
    ]
