# Generated by Django 5.0.1 on 2024-03-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0015_coverimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover_image",
                to="forum.post",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="forum.post",
            ),
        ),
    ]
