# Generated by Django 5.0.1 on 2024-03-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0016_alter_coverimage_post_alter_image_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover",
                to="forum.post",
            ),
        ),
    ]
