# Generated by Django 5.0.1 on 2024-03-03 03:07

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0017_alter_coverimage_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="coverimage",
            name="image_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=forum.models.upload_to,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="image_path",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=forum.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
