# Generated by Django 5.0.1 on 2024-03-03 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0019_alter_coverimage_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportpost",
            options={"ordering": ["-date"]},
        ),
    ]
