# Generated by Django 5.0.1 on 2024-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0002_doctorverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorverification",
            name="action",
            field=models.CharField(
                choices=[("verify", "Verify"), ("delete", "Delete")],
                default="verify",
                max_length=10,
            ),
        ),
    ]
