# Generated by Django 5.0.1 on 2024-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
